### ISSUE TITLE
Documents are not indexed

### ISSUE THREAD

**Issue by 21Damien** [dkd/php-cmis-client#62]
Hi,
Thank you for the job done.
I've a technical issue using this cmis client but i don't know how to solve it. 
When create a document i've no probelm with php-cmis but documents are not indexed by system.
Is-it normal ?  How can i get you more informations about my issue ?

Thank you.

**Comment by sascha-egerer** [comment]
@21Damien That does not sound like a problem in that lib.
Could you please provide more information? 
What Target-System are you using? What do you mean with documents do not get index? You mean in your target System?

**Comment by 21Damien** [comment]
I'm working with Alfresco Community - 5.0.0.
By using the word "index" i mean the document don't print into a search results in alfresco share. Neither title, full text content, description are queryable on those documents. We are using solr4 to index content.

The document is readeable when i go to the parent directory and select the document. 

Thank you.

**Comment by sascha-egerer** [comment]
I would say that is not related to this lib. You create a document and as far as i understood that is successful. Everything else like alfresco indexes do not have anything to do with this communication but are related to alfresco. So please recheck. I'll close that issue. Feel free to reopen it or add a comment if you think that the problem is related to that lib.
